version: "3.3"
services:
  web:
    image: node_dev
    container_name: node_dev
    volumes: 
      - C:\git\NewPfptCustomerProfile:/usr/src/app
    command: nodemon app/app.js

  mongodb:
    image: "mongo"
    container_name: mongodb
    volumes:
        - mongodata:/data/db
    env_file: .env
    ports:
      - "27017:27017"
    networks:
          - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodata:
