version: '3'

services:
    mongo:
        image: "mongo"
        container_name: mongo-database
        volumes:
            - mongodata:/data/db
        ports:
          - "27017:27017"
        networks:
              - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongodata: